<a href="https://colab.research.google.com/github/santraj18/Sentiment_Analysis/blob/main/Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
docs=['go india',
      'india india',
      'hip hip hurray',
      'jeetega bhai jeetega india jeetega',
      'bharat mata ki jai',
      'kohli kohli',
      'sachin sachin',
      'dhoni dhoni',

      'inquilab inquilab']

In [40]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()

In [41]:
tokenizer.fit_on_texts(docs)

In [42]:
len(tokenizer.word_index)

14

In [43]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[8, 1],
 [1, 1],
 [3, 3, 9],
 [2, 10, 2, 1, 2],
 [11, 12, 13, 14],
 [4, 4],
 [5, 5],
 [6, 6],
 [7, 7]]

In [44]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 8,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3,  9,  0,  0],
       [ 2, 10,  2,  1,  2],
       [11, 12, 13, 14,  0],
       [ 4,  4,  0,  0,  0],
       [ 5,  5,  0,  0,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0]], dtype=int32)

In [45]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [46]:
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [47]:
model.compile('adam','accuracy')

In [48]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
[[[ 0.01936911  0.04853204]
  [-0.04661604 -0.02123284]
  [-0.02791272  0.04413725]
  [-0.02791272  0.04413725]
  [-0.02791272  0.04413725]]

 [[-0.04661604 -0.02123284]
  [-0.04661604 -0.02123284]
  [-0.02791272  0.04413725]
  [-0.02791272  0.04413725]
  [-0.02791272  0.04413725]]

 [[-0.03055595 -0.00548876]
  [-0.03055595 -0.00548876]
  [-0.04797855  0.00109527]
  [-0.02791272  0.04413725]
  [-0.02791272  0.04413725]]

 [[ 0.02739442  0.02704741]
  [-0.02647798 -0.03637571]
  [ 0.02739442  0.02704741]
  [-0.04661604 -0.02123284]
  [ 0.02739442  0.02704741]]

 [[ 0.03032262 -0.01080059]
  [ 0.02674744  0.01121733]
  [-0.0452381   0.00491866]
  [-0.03588189  0.01858722]
  [-0.02791272  0.04413725]]

 [[-0.04025499  0.03231926]
  [-0.04025499  0.03231926]
  [-0.02791272  0.04413725]
  [-0.02791272  0.04413725]
  [-0.02791272  0.04413725]]

 [[ 0.04545697 -0.02180666]
  [ 0.04545697 -0.02180666]
  [-0.02791272  0.04413725]
  [-0.02791272  0.0441372

In [49]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [50]:
(X_train,y_train),(X_test,y_test)=imdb.load_data()

In [51]:
X_train=pad_sequences(X_train,padding='post',maxlen=50)
X_test=pad_sequences(X_test,padding='post',maxlen=50)

In [52]:
X_train.shape

(25000, 50)

In [53]:
model=Sequential()
import tensorflow as tf
model.add(Embedding(10000,output_dim=2,input_length=50))
##model.layers[0].set_weights([tf.Variable(tf.random.normal([10000, 5]))])
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_1 (SimpleRNN)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)